language: node_js
node_js:
  - "node"
services:
  - mongodb
notifications:
  webhooks:
    urls:
      - https://bots.rmunhoz.xyz/gitpull.php
    on_success: always
    on_failure: never
    on_start: never